[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pro_balance = "8ZwcssGn5vKE1d6oBNNTTjDsFyTDKSuPtoooZQe9MHXb"

[programs.devnet]
pro_balance = "8ZwcssGn5vKE1d6oBNNTTjDsFyTDKSuPtoooZQe9MHXb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pro-balance.ts tests/tokenDepositWithdraw.ts"
